
title: Aryan Barnwal
email: aryanbarnwal007@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  " What it takes to learn and grow together? Your trust and my eagerness to learn and work hard!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Aryan6290
github_username: Aryan6290

author:
    name: Aryan Barnwal
    email: aryanbarnwal007@gmail.com
social:
  github: Aryan6290
  twitter: Aryan6290
  facebook: aryan.barnwal.10
  linkedin: aryan-barnwal-932482193/
  instagram: paracetamol650

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
port: 8080
timezone: Asia/Kolkata

# Exclude from processing.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    -  Readme.md
    -  favicon.ico
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
